import { defineConfig } from "vite";
import mdx from "@mdx-js/rollup";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "path";

// Remark AST plugin to automatically unwrap unwanted <p> tags generated by MDX inside JSX components
function remarkUnwrapComponentChildren() {
  return (tree: any) => {
    const alwaysUnwrap = new Set([
      "Button", "Badge", "Alert", "AlertTitle", "AlertDescription", "DialogTitle",
      "DialogDescription", "CardTitle", "CardDescription", "TooltipTrigger",
      "TooltipPopup", "Toggle", "ToggleGroupItem", "TabsTab", "TabsTrigger",
      "AccordionTrigger", "BreadcrumbLink", "BreadcrumbPage", "Kbd", "EmptyStateTitle",
      "EmptyStateDescription", "ToastTitle", "ToastDescription"
    ]);

    function visit(node: any) {
      if (!node.children) return;

      if (node.type === "mdxJsxFlowElement" || node.type === "mdxJsxTextElement") {
        const realChildren = node.children.filter(
          (c: any) => !(c.type === "text" && c.value.trim() === "")
        );

        const shouldUnwrap =
          alwaysUnwrap.has(node.name) ||
          (realChildren.length === 1 && realChildren[0].type === "paragraph");

        if (shouldUnwrap) {
          const newChildren: any[] = [];
          for (const child of node.children) {
            if (child.type === "paragraph") {
              newChildren.push(...child.children);
            } else {
              newChildren.push(child);
            }
          }
          node.children = newChildren;
        }
      }

      for (const child of node.children) {
        visit(child);
      }
    }

    visit(tree);
  };
}

export default defineConfig({
  plugins: [
    mdx({
      providerImportSource: "@mdx-js/react",
      remarkPlugins: [remarkUnwrapComponentChildren],
    }),
    react(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "./src"),
      "@/tokens": path.resolve(import.meta.dirname, "./src/tokens"),
      "@docs": path.resolve(import.meta.dirname, "./docs"),
    },
  },
  build: {
    target: "esnext",
    outDir: "dist-app",
  },
  server: {
    port: 5173,
    host: true,
  },
});
