// Auto-generated by scripts/generate-api-docs.ts - do not edit directly
import apiData from "./api-reference.json";

export interface PropItem {
  name: string;
  type: string;
  defaultValue: string | null;
  required: boolean;
  description: string;
}

export interface ComponentApiDoc {
  name: string;
  file: string;
  description?: string;
  subcomponents?: string[];
  props: PropItem[];
}

export interface ApiReferenceData {
  components: Record<string, ComponentApiDoc>;
  byFile: Record<string, string[]>;
}

export const apiReferenceData = apiData as ApiReferenceData;
